version: "3.8"

services:
  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: web-app:1.0
    container_name: website
    volumes:
      - ./website.orig:/var/www/html
      #- ./website.test:/var/www/html
    ports:
      - 4051:80
    restart: always
